### ISSUE TITLE
Footer with social links

### ISSUE THREAD

**Issue by Swetlanda** [Swetlanda/stay-safe-online#4]
As a user, I want to see a footer with important social media links so I can follow them on social media.

Acceptance Criteria:
- [x] Footer with all social links
- [x] Responsive
- [x] Correct styling

Tasks:
- [x] Add footer
- [x] Format into correct colours
- [x] Add strapline/logo
- [x] Add links
- [x] The email address should use "mailto:" to open up a new email message with an <a href>

**Comment by PeterECoder** [comment]
Reopened as the email address should be a hyperlink
